name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  packages: write
  contents: read

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Name
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/flask-trivy-demo:${{ github.sha }}
          IMAGE_NAME_LC=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "image_name_lc=$IMAGE_NAME_LC" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          echo "Building Docker image: ${{ steps.vars.outputs.image_name_lc }}"
          docker build -t "${{ steps.vars.outputs.image_name_lc }}" .

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image: ${{ steps.vars.outputs.image_name_lc }}"
          docker push "${{ steps.vars.outputs.image_name_lc }}"
